_target_: foundry.models.tokenizer.EEGTokenizer
patch_duration: null
embed_dim: ${model.embed_dim}
channel_strategy:
  _target_: foundry.models.embeddings.SpatialProjectionStrategy
  num_channels: ${hyperparameters.num_channels}
  num_sources: ${model.embed_dim}
  projector:
    _target_: foundry.models.embeddings.SessionSpatialProjector
    session_configs: ${hyperparameters.session_configs}
    num_sources: ${model.tokenizer.channel_strategy.num_sources}
temporal_embedding:
  _target_: foundry.models.embeddings.CWTEmbedding
  embed_dim: ${model.embed_dim}
  num_sources: ${model.embed_dim}
  init_freqs: [2, 4, 8, 13, 20, 30, 50, 70, 100]
  target_time_tokens: 1000
  n_cycles: 7.0
