_target_: foundry.models.tokenizer.EEGTokenizer
patch_duration: ${hyperparameters.patch_duration}
embed_dim: ${model.embed_dim}
channel_strategy:
  _target_: foundry.models.embeddings.SpatialProjectionStrategy
  num_channels: ${hyperparameters.num_channels}
  num_sources: 10
  projector:
    _target_: foundry.models.embeddings.PerceiverSpatialProjector
    num_sources: ${model.tokenizer.channel_strategy.num_sources}
    d_attn: 64
    num_heads: 4
temporal_embedding:
  _target_: foundry.models.embeddings.PatchLinearEmbedding
  embed_dim: ${model.embed_dim}
  num_input_channels: ${model.tokenizer.channel_strategy.num_sources}
  patch_samples: ${patch_samples:${hyperparameters.patch_duration},${hyperparameters.sampling_rate}}
