_target_: foundry.models.EEGModel


input_embedding:
  _target_: foundry.models.embeddings.LinearEmbedding
  embed_dim: ${model.embed_dim}

readout_specs:
  - motor_imagery_5class

embed_dim: 128
sequence_length: 1.0
latent_step: 0.1
num_latents_per_step: 1
depth: 2
dim_head: 64
cross_heads: 1
self_heads: 8
ffn_dropout: 0.2
lin_dropout: 0.4
atn_dropout: 0.0
emb_init_scale: 0.02
t_min: 1e-4
t_max: 2.0627
context_mode: add
