_target_: foundry.models.EEGNetEncoder

readout_specs:
  - behavior_4class

# These parameters are based on the EEGNet paper: https://arxiv.org/abs/1611.07451.
# They need to be tuned for the specific dataset.
num_channels: 64
num_samples: 128
F1: 8
D: 2
F2: 16
kernel_length: 64
dropout_rate: 0.5