_target_: foundry.models.LaBraMForMaskedEEGModeling

num_channels: ${hyperparameters.num_channels}
num_samples: ${hyperparameters.num_samples}
embed_dim: 400
num_layers: 24
num_heads: 16
vocab_size: 8192
drop_path_prob: 0.0
