defaults:
  - tokenizer: fixed_patch_linear

_target_: foundry.models.POYOEEGModel

reconstruction_head: null

embed_dim: 128
sequence_length: ${hyperparameters.sequence_length}
latent_step: 0.1
num_latents_per_step: 8
depth: 2
dim_head: 64
cross_heads: 8
self_heads: 8
ffn_dropout: 0.2
lin_dropout: 0.4
atn_dropout: 0.2
emb_init_scale: 0.02
t_min: 1e-2
t_max: 0.5
