_target_: lightning.pytorch.loggers.WandbLogger
name: ${run.name}
project: ${run.project}
save_dir: ${oc.env:SCRATCH,./outputs}
offline: false
log_model: false
group: ${run.group}
tags: ${run.tags}
resume: allow
id: null
