_target_: lightning.pytorch.loggers.WandbLogger
name: ${run.name}
project: foundry
save_dir: ${oc.env:SCRATCH,./outputs}
offline: false
log_model: all
group: ${run.group}
tags: ${run.tags}
resume: allow
id: null
