name: ajile_pose_estimation

head:
  _target_: foundry.tasks.heads.ReadoutHead
  output_dim: 18

target_extractor:
  _target_: foundry.tasks.targets.TargetExtractor
  timestamp_key: pose_trajectories.timestamps
  value_key: pose_trajectories.values

loss:
  _target_: foundry.tasks.losses.MSETaskLoss

metrics:
  _target_: foundry.tasks.metrics.regression_metrics

metric_summary_modes:
  r2: max
  mse: min
  mae: min
  loss: min
