name: ajile_active_behavior

head:
  _target_: foundry.tasks.heads.ReadoutHead
  output_dim: 5

target_extractor:
  _target_: foundry.tasks.targets.TargetExtractor
  timestamp_key: active_behavior_trials.timestamps
  value_key: active_behavior_trials.behavior_id

loss:
  _target_: foundry.tasks.losses.CrossEntropyTaskLoss

metrics:
  _target_: foundry.tasks.metrics.classification_metrics
  num_classes: 5

class_names: [Eat, Talk, TV, Computer/Phone, Other Activity]
metric_summary_modes:
  acc: max
  f1: max
  auroc: max
  loss: min
