name: neurosoft_acoustic_stim_2band_rnd_b

class_mapping:
  mapping:
    stim_500Hz: class1
    stim_800Hz: class2
    stim_5000Hz: class2
    stim_8000Hz: class1
  order: [class1, class2]

head:
  _target_: foundry.tasks.heads.ReadoutHead

target_extractor:
  _target_: foundry.tasks.targets.TargetExtractor
  timestamp_key: acoustic_stim_trials.timestamps
  value_key: acoustic_stim_trials.behavior_labels

loss:
  _target_: foundry.tasks.losses.CrossEntropyTaskLoss

metrics:
  _target_: foundry.tasks.metrics.classification_metrics

metric_summary_modes:
  acc: max
  f1: max
  auroc: max
  loss: min
