name: neurosoft_acoustic_stim

head:
  _target_: foundry.tasks.heads.ReadoutHead
  output_dim: 26

target_extractor:
  _target_: foundry.tasks.targets.TargetExtractor
  timestamp_key: acoustic_stim_trials.timestamps
  value_key: acoustic_stim_trials.behavior_ids

loss:
  _target_: foundry.tasks.losses.CrossEntropyTaskLoss

metrics:
  _target_: foundry.tasks.metrics.classification_metrics
  num_classes: 26

class_names:
  - stim_100Hz
  - stim_200Hz
  - stim_300Hz
  - stim_400Hz
  - stim_500Hz
  - stim_650Hz
  - stim_800Hz
  - stim_1000Hz
  - stim_12000Hz
  - stim_13000Hz
  - stim_1500Hz
  - stim_2000Hz
  - stim_3000Hz
  - stim_4000Hz
  - stim_5000Hz
  - stim_7700Hz
  - stim_8000Hz
  - stim_9500Hz
  - stim_10000Hz
  - stim_15000Hz
  - stim_16000Hz
  - stim_18000Hz
  - stim_20000Hz
  - stim_30000Hz
  - stim_40000Hz
  - stim_wn
metric_summary_modes:
  acc: max
  f1: max
  auroc: max
  loss: min
