max_epochs: 1
output_dir: ./profiling_output

schedule:
  wait: 5 
  warmup: 5
  active: 5
  repeat: 1

record_shapes: false
profile_memory: false
with_stack: true
with_flops: false
row_limit: 30
sort_by_key: cuda_time_total
