_target_: hydra_plugins.foundry_launcher.packed_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/slurm_logs/%j
stderr_to_stdout: true
timeout_min: 180
signal_delay_s: 300
tasks_per_node: 1
cpus_per_task: ${hyperparameters.num_workers}
account: ${oc.env:CSCS_ACCOUNT,}
# partition: ${oc.env:CSCS_PARTITION,}
nodes: 1
mem_gb: 32
gres: gpu:1
array_parallelism: 10
name: ${hydra.job.name}
additional_parameters:
  requeue: true
setup:
  - "set -a"
  - "source .env"
  - "set +a"
  - "cd ${oc.env:SCRATCH}/Foundry"
  # - "uv sync"
  - "export RANK=0"
srun_args:
  - "--environment=${oc.env:SCRATCH}/edf-files/foundry.toml"
  # - "--network=disable_rdzv_get"