defaults:
  - submitit_slurm

_target_: hydra_plugins.foundry_launcher.packed_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/slurm_logs/%j
stderr_to_stdout: true
timeout_min: 180
signal_delay_s: 300
tasks_per_node: 1
cpus_per_task: ${hyperparameters.num_workers}
nodes: 1
mem_gb: 32
gres: gpu:1
array_parallelism: 256
additional_parameters:
  requeue: true
setup:
  - "set -a"
  - "source .env"
  - "set +a"
  - "export RANK=0"
