name: Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Install Ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: "--version"

    - name: Run Ruff Check
      run: ruff check --fix

    - name: Run Ruff Format
      run: ruff format